/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiLookupRouteImport } from './routes/api/lookup'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors/$vendorId'
import { Route as ApiApisSplatRouteImport } from './routes/api/apis/$'
import { Route as ApiVendorsIndexRouteImport } from './routes/api/vendors/index'
import { Route as ApiSpecsSpecIdNormalizedRouteImport } from './routes/api/specs/$specId/normalized'
import { Route as ApiSpecsSpecIdPublishedRouteImport } from './routes/api/specs/$specId/published'
import { Route as ApiVendorsVendorApisRouteImport } from './routes/api/vendors/$vendor/apis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupRoute = ApiLookupRouteImport.update({
  id: '/api/lookup',
  path: '/api/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApisSplatRoute = ApiApisSplatRouteImport.update({
  id: '/api/apis/$',
  path: '/api/apis/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendorsIndexRoute = ApiVendorsIndexRouteImport.update({
  id: '/api/vendors/',
  path: '/api/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpecsSpecIdNormalizedRoute =
  ApiSpecsSpecIdNormalizedRouteImport.update({
    id: '/api/specs/$specId/normalized',
    path: '/api/specs/$specId/normalized',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSpecsSpecIdPublishedRoute = ApiSpecsSpecIdPublishedRouteImport.update({
  id: '/api/specs/$specId/published',
  path: '/api/specs/$specId/published',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVendorsVendorApisRoute = ApiVendorsVendorApisRouteImport.update({
  id: '/api/vendors/$vendor/apis',
  path: '/api/vendors/$vendor/apis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/lookup': typeof ApiLookupRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/': typeof VendorsIndexRoute
  '/api/apis/$': typeof ApiApisSplatRoute
  '/api/vendors/': typeof ApiVendorsIndexRoute
  '/api/specs/$specId/normalized': typeof ApiSpecsSpecIdNormalizedRoute
  '/api/specs/$specId/published': typeof ApiSpecsSpecIdPublishedRoute
  '/api/vendors/$vendor/apis': typeof ApiVendorsVendorApisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/lookup': typeof ApiLookupRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors': typeof VendorsIndexRoute
  '/api/apis/$': typeof ApiApisSplatRoute
  '/api/vendors': typeof ApiVendorsIndexRoute
  '/api/specs/$specId/normalized': typeof ApiSpecsSpecIdNormalizedRoute
  '/api/specs/$specId/published': typeof ApiSpecsSpecIdPublishedRoute
  '/api/vendors/$vendor/apis': typeof ApiVendorsVendorApisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/lookup': typeof ApiLookupRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/': typeof VendorsIndexRoute
  '/api/apis/$': typeof ApiApisSplatRoute
  '/api/vendors/': typeof ApiVendorsIndexRoute
  '/api/specs/$specId/normalized': typeof ApiSpecsSpecIdNormalizedRoute
  '/api/specs/$specId/published': typeof ApiSpecsSpecIdPublishedRoute
  '/api/vendors/$vendor/apis': typeof ApiVendorsVendorApisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/api/$'
    | '/api/health'
    | '/api/lookup'
    | '/vendors/$vendorId'
    | '/vendors/'
    | '/api/apis/$'
    | '/api/vendors/'
    | '/api/specs/$specId/normalized'
    | '/api/specs/$specId/published'
    | '/api/vendors/$vendor/apis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/api/$'
    | '/api/health'
    | '/api/lookup'
    | '/vendors/$vendorId'
    | '/vendors'
    | '/api/apis/$'
    | '/api/vendors'
    | '/api/specs/$specId/normalized'
    | '/api/specs/$specId/published'
    | '/api/vendors/$vendor/apis'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/api/$'
    | '/api/health'
    | '/api/lookup'
    | '/vendors/$vendorId'
    | '/vendors/'
    | '/api/apis/$'
    | '/api/vendors/'
    | '/api/specs/$specId/normalized'
    | '/api/specs/$specId/published'
    | '/api/vendors/$vendor/apis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLookupRoute: typeof ApiLookupRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  ApiApisSplatRoute: typeof ApiApisSplatRoute
  ApiVendorsIndexRoute: typeof ApiVendorsIndexRoute
  ApiSpecsSpecIdNormalizedRoute: typeof ApiSpecsSpecIdNormalizedRoute
  ApiSpecsSpecIdPublishedRoute: typeof ApiSpecsSpecIdPublishedRoute
  ApiVendorsVendorApisRoute: typeof ApiVendorsVendorApisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookup': {
      id: '/api/lookup'
      path: '/api/lookup'
      fullPath: '/api/lookup'
      preLoaderRoute: typeof ApiLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apis/$': {
      id: '/api/apis/$'
      path: '/api/apis/$'
      fullPath: '/api/apis/$'
      preLoaderRoute: typeof ApiApisSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendors/': {
      id: '/api/vendors/'
      path: '/api/vendors'
      fullPath: '/api/vendors/'
      preLoaderRoute: typeof ApiVendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/specs/$specId/normalized': {
      id: '/api/specs/$specId/normalized'
      path: '/api/specs/$specId/normalized'
      fullPath: '/api/specs/$specId/normalized'
      preLoaderRoute: typeof ApiSpecsSpecIdNormalizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/specs/$specId/published': {
      id: '/api/specs/$specId/published'
      path: '/api/specs/$specId/published'
      fullPath: '/api/specs/$specId/published'
      preLoaderRoute: typeof ApiSpecsSpecIdPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vendors/$vendor/apis': {
      id: '/api/vendors/$vendor/apis'
      path: '/api/vendors/$vendor/apis'
      fullPath: '/api/vendors/$vendor/apis'
      preLoaderRoute: typeof ApiVendorsVendorApisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLookupRoute: ApiLookupRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  ApiApisSplatRoute: ApiApisSplatRoute,
  ApiVendorsIndexRoute: ApiVendorsIndexRoute,
  ApiSpecsSpecIdNormalizedRoute: ApiSpecsSpecIdNormalizedRoute,
  ApiSpecsSpecIdPublishedRoute: ApiSpecsSpecIdPublishedRoute,
  ApiVendorsVendorApisRoute: ApiVendorsVendorApisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
